-- ==============================================
-- CRITICAL SECURITY FIX: Remove public/anon access to sensitive tables
-- The public profile feature uses static snapshots generated by edge function,
-- NOT direct table access. Tables should only be accessible to authenticated users.
-- ==============================================

-- 1. Drop public access policies from goals table
DROP POLICY IF EXISTS "Anyone can view public goals for public profiles" ON public.goals;

-- 2. Drop public access policies from profiles table  
DROP POLICY IF EXISTS "Anyone can view profiles with public profile settings" ON public.profiles;

-- 3. Drop public access policies from public_profile_interests table
DROP POLICY IF EXISTS "Anyone can view public interests for public profiles" ON public.public_profile_interests;

-- 4. Drop public access policies from public_profile_settings table
DROP POLICY IF EXISTS "Anyone can view public profile settings for public profiles" ON public.public_profile_settings;

-- 5. Fix policies that use "public" role instead of "authenticated" role
-- These should require authentication, not be open to anonymous users

-- Fix goal_milestones policies to require authentication
DROP POLICY IF EXISTS "Shared users can view milestones of shared goals" ON public.goal_milestones;
CREATE POLICY "Shared users can view milestones of shared goals"
ON public.goal_milestones FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.goal_shares
    WHERE goal_shares.goal_id = goal_milestones.goal_id
    AND goal_shares.shared_with_user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can delete milestones of their own goals" ON public.goal_milestones;
CREATE POLICY "Users can delete milestones of their own goals"
ON public.goal_milestones FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.goals
    WHERE goals.id = goal_milestones.goal_id
    AND goals.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can insert milestones for their own goals" ON public.goal_milestones;
CREATE POLICY "Users can insert milestones for their own goals"
ON public.goal_milestones FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.goals
    WHERE goals.id = goal_milestones.goal_id
    AND goals.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can update milestones of their own goals" ON public.goal_milestones;
CREATE POLICY "Users can update milestones of their own goals"
ON public.goal_milestones FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.goals
    WHERE goals.id = goal_milestones.goal_id
    AND goals.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can view milestones of their own goals" ON public.goal_milestones;
-- Keep the authenticated version only

-- Fix goal_reflections policies
DROP POLICY IF EXISTS "Users can delete their own goal reflections" ON public.goal_reflections;
CREATE POLICY "Users can delete their own goal reflections"
ON public.goal_reflections FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own goal reflections" ON public.goal_reflections;
CREATE POLICY "Users can insert their own goal reflections"
ON public.goal_reflections FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own goal reflections" ON public.goal_reflections;
CREATE POLICY "Users can update their own goal reflections"
ON public.goal_reflections FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own goal reflections" ON public.goal_reflections;
-- Keep authenticated version only

-- Fix goals policies
DROP POLICY IF EXISTS "Shared users can view goals shared with them" ON public.goals;
CREATE POLICY "Shared users can view goals shared with them"
ON public.goals FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.goal_shares
    WHERE goal_shares.goal_id = goals.id
    AND goal_shares.shared_with_user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can delete their own goals" ON public.goals;
CREATE POLICY "Users can delete their own goals"
ON public.goals FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own goals" ON public.goals;
CREATE POLICY "Users can insert their own goals"
ON public.goals FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own goals" ON public.goals;
CREATE POLICY "Users can update their own goals"
ON public.goals FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

-- Fix module_reflections policies
DROP POLICY IF EXISTS "Admins can view all module reflections" ON public.module_reflections;
CREATE POLICY "Admins can view all module reflections"
ON public.module_reflections FOR SELECT
TO authenticated
USING (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Coaches can view client reflections" ON public.module_reflections;
CREATE POLICY "Coaches can view client reflections"
ON public.module_reflections FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.module_progress mp
    JOIN public.client_enrollments ce ON ce.id = mp.enrollment_id
    JOIN public.client_coaches cc ON cc.client_id = ce.client_user_id
    WHERE mp.id = module_reflections.module_progress_id
    AND cc.coach_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM public.module_progress mp
    JOIN public.client_enrollments ce ON ce.id = mp.enrollment_id
    JOIN public.program_instructors pi ON pi.program_id = ce.program_id
    WHERE mp.id = module_reflections.module_progress_id
    AND pi.instructor_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM public.module_progress mp
    JOIN public.client_enrollments ce ON ce.id = mp.enrollment_id
    JOIN public.program_coaches pc ON pc.program_id = ce.program_id
    WHERE mp.id = module_reflections.module_progress_id
    AND pc.coach_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Instructors and coaches can view reflections for their modules" ON public.module_reflections;
CREATE POLICY "Instructors and coaches can view reflections for their modules"
ON public.module_reflections FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.module_progress mp
    WHERE mp.id = module_reflections.module_progress_id
    AND (
      EXISTS (
        SELECT 1 FROM public.module_instructors mi
        WHERE mi.module_id = mp.module_id
        AND mi.instructor_id = auth.uid()
      )
      OR EXISTS (
        SELECT 1 FROM public.module_coaches mc
        WHERE mc.module_id = mp.module_id
        AND mc.coach_id = auth.uid()
      )
    )
  )
);

DROP POLICY IF EXISTS "Users can delete their own module reflections" ON public.module_reflections;
CREATE POLICY "Users can delete their own module reflections"
ON public.module_reflections FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own module reflections" ON public.module_reflections;
CREATE POLICY "Users can insert their own module reflections"
ON public.module_reflections FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own module reflections" ON public.module_reflections;
CREATE POLICY "Users can update their own module reflections"
ON public.module_reflections FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own module reflections" ON public.module_reflections;
CREATE POLICY "Users can view their own module reflections"
ON public.module_reflections FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Fix profiles policies to require authentication for group members view
DROP POLICY IF EXISTS "Users can view profiles of group members in their groups" ON public.profiles;
CREATE POLICY "Users can view profiles of group members in their groups"
ON public.profiles FOR SELECT
TO authenticated
USING (
  id IN (
    SELECT gm2.user_id
    FROM public.group_memberships gm1
    JOIN public.group_memberships gm2 ON gm1.group_id = gm2.group_id
    WHERE gm1.user_id = auth.uid()
    AND gm1.status = 'active'
    AND gm2.status = 'active'
  )
);

-- Fix public_profile_interests policies
DROP POLICY IF EXISTS "Profile interests readable by owner and admin" ON public.public_profile_interests;
CREATE POLICY "Profile interests readable by owner and admin"
ON public.public_profile_interests FOR SELECT
TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Users can manage their own public interests" ON public.public_profile_interests;
CREATE POLICY "Users can manage their own public interests"
ON public.public_profile_interests FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Fix public_profile_settings policies
DROP POLICY IF EXISTS "Profile settings readable by owner and admin" ON public.public_profile_settings;
CREATE POLICY "Profile settings readable by owner and admin"
ON public.public_profile_settings FOR SELECT
TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Users can manage their own public profile settings" ON public.public_profile_settings;
CREATE POLICY "Users can manage their own public profile settings"
ON public.public_profile_settings FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Fix user_interests policies
DROP POLICY IF EXISTS "Users can manage their own interests" ON public.user_interests;
CREATE POLICY "Users can manage their own interests"
ON public.user_interests FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);